### ISSUE TITLE
only red pixels

### ISSUE THREAD

**Issue by donbing** [robweber/omni-epd#58] opened 2022-02-25 00:43 UTC
Hi, I've got a `waveshare_epd.epd2in7b_V2`  that i'm trying to show a picture on. 

when i configure the device for `red` mode using an ini file all I get is red pixels on the display, should it also display black?

e.g:
source image:
![origonal](https://user-images.githubusercontent.com/413860/155631192-eba7ae5f-c4e8-42dd-a680-4e5672a6e3d5.png)
resized and converted to RBG:
![converted](https://user-images.githubusercontent.com/413860/155631198-eff206e8-c9ed-40b2-93f6-858190703426.png)
displayed:
![rendered](https://user-images.githubusercontent.com/413860/155631238-e67ae672-00a2-4d24-a4a7-47de91432731.jpg)

**Comment by robweber** [comment] 2022-02-25 15:45
Thanks for pointing this out, you're right there is definitely an issue there. 

I _think_ I have it figured out but if you could please run a test on your system that would be great. I don't have your specific device but using the `omni_epd.mock` device with a custom palette I was able to to determine two different things were happening during the color filtering functions: 

1. images not currently in the `RGB` mode need to be converted to that mode before filtering
2. The wrong variable was being referenced when backfilling the unused colors

The result of both of these was that white was essentially being interpreted as black on the image. On the EPD this meant that anything black would be drawn as white when in the 3 color mode. BW only images were unaffected since they aren't using color filtering, simply converted to 2 color. 

The fix should be in [this commit](https://github.com/robweber/omni-epd/commit/25a365e79668b13b8ad45d8ea6350ae2ed9f8190). If you could update your local install and rebuild the library it should work now - I hope!

**Comment by donbing** [comment] 2022-02-26 18:58
I'm going to test on my 2.7 waveshare and 4.2 inky once I can get numpy to download correctly, the setup seems to be getting stuck there for me atm.

**Comment by donbing** [comment] 2022-02-26 19:13
ok, got it to run on my Pi4, but I get the following error from the test util

``` sh
pi@raspberrypi:~/omni-epd $ omni-epd-test -e inky.what_red
Loaded inky.what_red with width 400 and height 300
Drawing rectangle of width 300.0 and height 225.0
Traceback (most recent call last):
  File "/usr/local/bin/omni-epd-test", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/omni_epd/test_utility.py", line 127, in main
    test.draw()
  File "/usr/local/lib/python3.7/dist-packages/omni_epd/test_utility.py", line 83, in draw
    draw = self.__draw_rectangle(draw, self.epd.width, self.epd.height, 0, 0, .75, .25)
  File "/usr/local/lib/python3.7/dist-packages/omni_epd/test_utility.py", line 58, in __draw_rectangle
    imgObj.rectangle((rX, rY, rWidth + rX, rHeight + rY), outline=ImageColor.getrgb("black"), width=2)
TypeError: rectangle() got an unexpected keyword argument 'width'
```

both my pi zero2s are getting stuck at the numpy install 

```py
pi@comitup-624:~/omni-epd $ sudo pip3 install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/omni-epd
  Installing build dependencies ... done
Collecting Pillow (from omni-epd==0.2.7b1)
  Using cached https://www.piwheels.org/simple/pillow/Pillow-9.0.1-cp37-cp37m-linux_armv7l.whl
Collecting waveshare-epd@ git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd from git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd (from omni-epd==0.2.7b1)
  Cloning https://github.com/waveshare/e-Paper.git to /tmp/pip-install-lsb5upt7/waveshare-epd
Collecting inky[rpi] (from omni-epd==0.2.7b1)
  Using cached https://files.pythonhosted.org/packages/9e/db/ab689bad7935ce13cf0356bf2ad6e13ee2a115f3a33de7596676ad464921/inky-1.3.1-py3-none-any.whl
Collecting hitherdither@ git+https://github.com/hbldh/hitherdither from git+https://github.com/hbldh/hitherdither (from omni-epd==0.2.7b1)
  Cloning https://github.com/hbldh/hitherdither to /tmp/pip-install-lsb5upt7/hitherdither
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from waveshare-epd@ git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd->omni-epd==0.2.7b1) (0.7.0)
Collecting numpy (from waveshare-epd@ git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd->omni-epd==0.2.7b1)
  Using cached https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip
  Installing build dependencies ... done
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (from waveshare-epd@ git+https://github.com/waveshare/e-Paper.git#subdirectory=RaspberryPi_JetsonNano/python&egg=waveshare-epd->omni-epd==0.2.7b1) (3.5)
Collecting smbus2 (from inky[rpi]->omni-epd==0.2.7b1)
  Using cached https://files.pythonhosted.org/packages/c8/bf/62ef029fb7077fc87c3539f7365859bccc6cedb2bb20796b737b788c8d09/smbus2-0.4.1-py2.py3-none-any.whl
Building wheels for collected packages: omni-epd, waveshare-epd, hitherdither, numpy
  Running setup.py bdist_wheel for omni-epd ... done
  Stored in directory: /root/.cache/pip/wheels/45/58/69/3b9460b88cc0aee0ed20ed6e27c300b100ddac04e4d43d261f
  Running setup.py bdist_wheel for waveshare-epd ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-d_a3y7oj/wheels/4b/4d/5a/fc28bbb9a5787d248880f44b98931eab72d5d884de27a4845b
  Running setup.py bdist_wheel for hitherdither ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-d_a3y7oj/wheels/2d/7f/db/ba7bd2317fae19a700c11482577b6115f907ff836b2221c184
  Running setup.py bdist_wheel for numpy ... /
```

**Comment by donbing** [comment] 2022-02-26 19:42
I think [setup.cfg](https://github.com/robweber/omni-epd/blob/main/setup.cfg) needs to pin it's dependencies..

**Comment by donbing** [comment] 2022-02-26 19:48
PR to fix that here https://github.com/robweber/omni-epd/pull/59

**Comment by donbing** [comment] 2022-02-26 19:53
so after fixing that, and running the draw_image example, I only get black pixels on the red inkywhat
```sh
pi@raspberrypi:~/omni-epd/examples/basic_example $ python3 draw_image.py
Loading display
Loading image
Writing to display
``
![20220226_195145](https://user-images.githubusercontent.com/413860/155857244-f2bcbb1b-f526-42f7-8635-f1fd35a2612d.jpg)

**Comment by donbing** [comment] 2022-02-26 19:58
i added the following ini file to the example
```ini
[EPD]
type=inky.what_red
mode=red

[Display]
rotate=180

[Image Enhancements]
contrast=1.5
sharpness=2
```


and now i get bits of red in the pic!
![20220226_195649](https://user-images.githubusercontent.com/413860/155857359-605a7aab-9f92-4901-9d0c-d203da42aa5d.jpg)

i'll try with the waveshare a bit later, to verify that it works there too.

**Comment by donbing** [comment] 2022-02-26 20:43
looks right on the `waveshare_epd.epd2in7b_V2` too!

![20220226_204227](https://user-images.githubusercontent.com/413860/155858488-1f9e26f5-df75-46e8-9844-8d430e03d5c3.jpg)

**Comment by donbing** [comment] 2022-02-26 21:05
altho.. why does one have a black background and one white :)

**Comment by robweber** [comment] 2022-02-27 17:20
Interesting....it's easily fixed by flipping how the image is generated but wonder how many other displays require the inverted image?

Is this an oversight or intentional in the Waveshare driver do you think? If it's intentional we'll have to fix here.

**Comment by aaronr8684** [comment] 2022-02-27 20:35
@robweber Well I think I have an answer to that question and why I was seeing weird behavior on my 7.5b in the other issues. I went through every driver file in the WS lib and wow is it inconsistent (as you know). Anyway, I added to my already existing google sheet some additional info on if each driver does inverting in the buffer and then possibly again in the display methods. 

For reference, here are the ways that they invert (or it seems). I really didn't dig into the code a ton. I just marked it if it appeared to be inverting the bits:

v1.1 - `buf[int((x + y * self.width) / 8)] &= ~(0x80 >> (x % 8))` - invert
v1.2 - `buf[int(x / 8) + y * linewidth] &= ~(0x80 >> (x % 8))` - invert 
v2 - `buf[int((x + y * self.width) / 4)] &= ~(0xC0 >> (x % 4 * 2))` - invert and grey to red
v3 - `buf[i] ^= 0xFF`
v4 - `data_t = buf[Add]&(~(0xF0 >> ((newx % 2)*4)))` - 4" color

The above "versions" of inverting are what I reference in my sheet here (drivers tab) - https://docs.google.com/spreadsheets/d/1r4EKPGZvz_xQZA58WPyuTVPhXGKCWd7-Z-btqgaFfKw/edit#gid=1378358670

I tried to highlight differences from the norm, so outliers were more easily identified. 

Sorry it took me so long to respond, but I wanted to have some concrete info before I speculated

**Comment by missionfloyd** [comment] 2022-02-28 03:49
I think it's probably an oversight. Usually, with e-paper 1 is black and 0 is white.

@aaronr8684 does waveshare's example display correctly?

**Comment by aaronr8684** [comment] 2022-02-28 04:32
On my 7.5b? Yea. I ran a bunch of tests with Omni with it as well. I know that a black image pixel is on for the black, red, or yellow ePaper pixels, but it seems like every driver handles it in a different way. I'm not really sure at this point what the best approach is for Omni, but I figured the first step was documenting the differences.

**Comment by missionfloyd** [comment] 2022-02-28 05:34
No, the 2.7b.

**Comment by aaronr8684** [comment] 2022-02-28 14:23
@missionfloyd I don't have the 2.7b. Yes, a little consistency would be nice. They really should have one method of display per screen type. BW, R/Y, 4-Grey, Color 

@donbing have you tried the v1 `waveshare_epd.epd2in7b` driver?

**Comment by donbing** [comment] 2022-02-28 17:42
@aaronr8684 the non-V2 version? if so, no. but I will

**Comment by donbing** [comment] 2022-02-28 19:18
pi@raspberrypi:~/omni-epd/examples $ omni-epd-test -e waveshare_epd.epd2in7b -i PIA03519_small.jpg 
Loaded waveshare_epd.epd2in7b with width 176 and height 264
...
the command never terminates, and the screen is not refreshed (my device is a v2)

**Comment by donbing** [comment] 2022-02-28 19:32
I did a bit more testing.. 

## e.g. 1. red mode gives white background

Given this `omni-epg.ini`
```ini
[EPD]
type=waveshare_epd.epd2in7b_V2
mode=red
```
When I execute
```sh
omni-epd-test -e waveshare_epd.epd2in7b_V2 -i PIA03519_small.jpg
```
Then I get this image
![20220228_192240](https://user-images.githubusercontent.com/413860/156045980-c9d1d2ac-e2d5-46f4-a088-f97950fa824e.jpg)

## e.g. 2. BW mode gives black background
Given this `omni-epg.ini`
```ini
[EPD]
type=waveshare_epd.epd2in7b_V2
```
When I execute
```sh
omni-epd-test -e waveshare_epd.epd2in7b_V2 -i PIA03519_small.jpg
```
Then I get this image
![20220228_191528](https://user-images.githubusercontent.com/413860/156045948-0e426763-331c-4c2c-b838-7c42f134903a.jpg)

**Comment by donbing** [comment] 2022-02-28 19:38
testing on a 4.2" red inkywhat gives back backgrounds for both red and BW.

**Comment by donbing** [comment] 2022-02-28 19:43
Testing on a 5.6" inky impression gives black backgrounds for both color and BQ modes too

**Comment by donbing** [comment] 2022-02-28 19:45
I also have a waveshare pico-epaper-4.2. But that's a faff to wire up, so I'll leave it unless anyone specifically wants it testing..

**Comment by aaronr8684** [comment] 2022-02-28 19:51
Can you modify the Omni-EPD library code in `/usr/local/lib/python<ver>/dist-packages/omni_epd/displays/waveshare_display.py` on line 214 to `img_black.putpalette((255, 255, 255, 0, 0, 0))` 

You'll need to change <ver> it to your version, either 3 or 3.X

Does that fix the background in "red" mode?

**Comment by aaronr8684** [comment] 2022-02-28 19:59
In summary, the issue lies in how the individual libraries handle the image to buffer conversion. The correct result (that you see in some waveshare libraries and all tested inky libraries) is to convert the black in an image (0x00) to ePaper black (0xFF). The Omni library is correctly generating the black background PIL image (see attached), but some of the libraries are not inverting it correctly before sending it to the screen. The correct fix is to create a PR in the official repo for waveshare, but the faster fix might be to figure out which screens are incorrect and break them out into a separate class implementation. 
 
![img_black.show() output](https://user-images.githubusercontent.com/57102156/156049905-c3ddc6c2-71dd-4782-acd9-6f4069c3ab26.png)

**Comment by aaronr8684** [comment] 2022-02-28 20:07
> I also have a waveshare pico-epaper-4.2. But that's a faff to wire up, so I'll leave it unless anyone specifically wants it testing..

Yea my 5.65" color is a pico hat, that I have to wire up to work with my pi4. After I did it once, I just snapped a photo so that I didn't have to work with the pin table and could just visually see the pinout. I've attached it if it helps. Ignore the 5V/Ground fan wires 😄 

Visual Pinout (uses 3.3V):
![2022-02-06 21 15 35](https://user-images.githubusercontent.com/57102156/156051246-ecb57777-ac02-4c7c-9f15-b578d4e54544.jpg)

**Comment by donbing** [comment] 2022-02-28 20:19
@aaronr8684 I changed the code you suggested. And yep, I now get black backgrounds for both black and red modes!

**Comment by aaronr8684** [comment] 2022-02-28 20:26
@donbing I assumed that would work. It shouldn't have any effect on the bw mode, but it's helpful to test. Thanks! 

The `epd5in83c` also behaves like your 2.7b_V2 so that's at least 2 screens that have been confirmed to have a different implementation. I have someone testing the 2.7b_V1 to see if it's the same.

I think at this point, we'll have to wait to see how @robweber would like to approach it. Once a direction is given, I'm happy to do the coding if no one has the time at the moment. I'm working on adding Omni to another project, so I'm glad that we are working through these bugs first to make testing downstream a little smoother.

**Comment by aaronr8684** [comment] 2022-02-28 20:37
> @aaronr8684 I changed the code you suggested. And yep, I now get black backgrounds for both black and red modes

If you're curious, this is what the `img_black.show()` output looks like with the code you changed:
![img_black-putpalette-white255_then_black0](https://user-images.githubusercontent.com/57102156/156054961-948717c5-3caa-42cb-be87-a4b8e5e9babe.png)

**Comment by donbing** [comment] 2022-02-28 20:38
Glad I could help 👍, I'd been looking at adding omni to my [crypto-ticker project](https://github.com/donbing/Bitbot). 

I really appreciate the pic btw, I've got the 4.2" pico red up and running with the `waveshare_epd.epd4in2b_V2` driver 🤩.

**Comment by donbing** [comment] 2022-02-28 20:40
you'l be happy to know that waveshare_epd.epd4in2b_V2 also suffers from the black-conversion issue 🤕

**Comment by aaronr8684** [comment] 2022-02-28 20:42
> Glad I could help 👍, I'd been looking at adding omni to my [crypto-ticker project](https://github.com/donbing/Bitbot).

Yea I was taking a look at your project and really like the look of it. I was thinking it would be cool to bring in that functionality to the epd_display / PaperPi project as a plugin [#59](https://github.com/txoof/epd_display/issues/59). It would be a great addition and offers a lot more features over the current crypto option. Maybe someday when all the other work is done 🤷‍♂️

**Comment by robweber** [comment] 2022-02-28 20:47
> The correct fix is to create a PR in the official repo for waveshare, but the faster fix might be to figure out which screens are incorrect and break them out into a separate class implementation.

Really appreciate all the testing everyone is putting into this. I never would have thought a simple "red isn't showing up" issue would have ballooned so much. I think the best approach at this point might be to simply handle the screens that are incorrect. In the [device mapping](https://github.com/robweber/omni-epd/blob/main/src/omni_epd/displays/waveshare_display.py#L152) another key could be added to specify which ones and then use the correct palette filter to get the right image for the buffer. To be fair I _hate_ this type of solution since as soon as Waveshare changes it will be out of date but it's a compromise on usability. 

@aaronr8684  - that spreadsheet is nice, must have taken some time to dig into all the displays. Is that something I could link to on the Wiki of this project? More for informational than anything.

**Comment by aaronr8684** [comment] 2022-02-28 20:47
> You'll be happy to know that waveshare_epd.epd4in2b_V2 also suffers from the black-conversion issue 🤕

I added another column to track which screens display correctly and which do not. More info the better, right? 😅

**Comment by aaronr8684** [comment] 2022-02-28 20:53
> > The correct fix is to create a PR in the official repo for waveshare, but the faster fix might be to figure out which screens are incorrect and break them out into a separate class implementation.
> 
> Really appreciate all the testing everyone is putting into this. I never would have thought a simple "red isn't showing up" issue would have ballooned so much. I think the best approach at this point might be to simply handle the screens that are incorrect. In the [device mapping](https://github.com/robweber/omni-epd/blob/main/src/omni_epd/displays/waveshare_display.py#L152) another key could be added to specify which ones and then use the correct palette filter to get the right image for the buffer. To be fair I _hate_ this type of solution since as soon as Waveshare changes it will be out of date but it's a compromise on usability.
> 
> @aaronr8684 - that spreadsheet is nice, must have taken some time to dig into all the displays. Is that something I could link to on the Wiki of this project? More for informational than anything.

@robweber Absolutely! It's not at all "cleaned up" and although I tried to be as accurate as possible, I'm sure some of the code interpretation is probably wrong from my "at a glance" approach. I've change the read-only access to comment access so it can be more of a collaborative document. I'll also add the versions of inversion to the doc for easier reference.

**Comment by missionfloyd** [comment] 2022-03-01 00:32
@aaronr8684 Sorry, I responded to the wrong person.

@donbing Have you checked if waveshare's examples work right on your 2.7b? It would help to know if it's our problem or theirs.

**Comment by aaronr8684** [comment] 2022-03-01 02:26
@donbing Sorry for the double ping. A photo would be nice if you run the waveshare test file on the 3rd test

**Comment by donbing** [comment] 2022-03-01 10:04
np, here's a few snaps from the waveshare example.



![20220301_095820](https://user-images.githubusercontent.com/413860/156147845-67ca4d71-3951-4255-9945-9fb7dc1dace5.jpg)
![20220301_095855](https://user-images.githubusercontent.com/413860/156147849-d00797f4-e0e4-479c-9fe7-30786dbfbdbc.jpg)
![20220301_095912](https://user-images.githubusercontent.com/413860/156147855-ad4d320a-ec30-4184-9de8-cd8fdada4a8c.jpg)

**Comment by aaronr8684** [comment] 2022-03-01 19:42
I ran some tests with different threshold values...the higher the number the more black that will result

224:
![224](https://user-images.githubusercontent.com/57102156/156237107-3dc37377-5ed4-42ce-bbb6-194d87472f12.png)

128:
![128](https://user-images.githubusercontent.com/57102156/156237137-dd83bfef-d084-4b74-aab6-4274afd1e60c.png)

64:
![64](https://user-images.githubusercontent.com/57102156/156237153-a6c2b664-c08c-400c-908e-e737146c30a8.png)

32:
![32](https://user-images.githubusercontent.com/57102156/156237169-4606ce59-45b6-492d-a45d-39f1a38db49d.png)


For bw images, 128 is nice, but with a third color, I think the best results are from the 32/64 range.

**Comment by missionfloyd** [comment] 2022-03-02 06:16
Are we sure 827321789983b9368f5e0f8d68421eec13bc6f40 didn't break something?

@donbing can you try changing lines 214 and 217 in `waveshare_display.py` back to 
`img_black.putpalette((255, 255, 255, 0, 0, 0, 255, 255, 255) + (255, 255, 255)*253)`
and
`img_color.putpalette((255, 255, 255, 255, 255, 255, 0, 0, 0) + (255, 255, 255)*253)`
respectively?

**Comment by donbing** [comment] 2022-03-02 13:06
> img_color.putpalette((255, 255, 255, 255, 255, 255, 0, 0, 0) + (255, 255, 255)*253)

line 217 is already identical to this?

**Comment by donbing** [comment] 2022-03-02 13:23
using 
```py
img_black.putpalette((0, 0, 0, 255, 255, 255))
```
results in a white background

**Comment by aaronr8684** [comment] 2022-03-02 13:24
@donbing were you able to make the changes I suggested?

**Comment by donbing** [comment] 2022-03-02 13:25
@aaronr8684 will try now, 2 mins

**Comment by donbing** [comment] 2022-03-02 13:28
Alrighty, so Given:
```py
            img_black = img_black.convert('L')
            threshold = 32
            img_black = img_black.point( lambda p: 255 if p > threshold else 0)
            img_black = img_black.convert('1')
```
Then:
![20220302_132650](https://user-images.githubusercontent.com/413860/156370655-e7839db6-4d54-42b0-9568-4982b9c215d4.jpg)

**Comment by aaronr8684** [comment] 2022-03-02 13:40
That's great @donbing, that means that this solution works on yours and mine which have had the opposite results with the putpalette options we've tested so far. 

For completeness of the solution (and to incorporate some changes I've tested since), can you replace the entire `else` block starting around line 208 with the following code:

``` python
            # apply the color filter to get a 3 color image
            image = self._filterImage(image)
            image = image.convert('L')
            
            # create copies to send separately to the display method
            img_black = image.copy()
            img_color = image.copy()
            
            # switch grey colors to black or white based on threshold
            threshold = 16
            img_black = img_black.point( lambda p: 255 if p > threshold else 0 )
           
            # switch grey colors to black or white based on hardcoded thresholds. Should work with red or yellow screens
            img_color = img_color.point( lambda p: 0 if p > 18 and p < 235 else 255 )
            
            self._device.display(self._device.getbuffer(img_black), self._device.getbuffer(img_color))
```

**Comment by aaronr8684** [comment] 2022-03-02 14:10
@donbing Sweet! Thanks for your help with this!

@dr-boehmerie, if you have some time, do you want to test this solution with your yellow screen?

@robweber what are your thoughts? I'm not saying that the solution above is the best, but it at least seems to work with all screen methods. I'm happy to discuss how you'd like to integrate this into the project before submitting a PR and also sitting on it a bit to see if we can come up with any additional ideas or improvements. Maybe set up a discussion item or we can just keep discussing on this issue.

**Comment by aaronr8684** [comment] 2022-03-02 14:58
As a summary of what I believe is happening here...

Using putpalette with a 'P' image mode assigns a custom palette to the image, but (and this is the important part) doesn't change the underlying image data. I think some of the waveshare drivers were able to handle this just fine and some couldn't. So changing the way the palette was setup would always break some of the screens. The solution is to pass a bw image to the get buffer methods of each driver file. 

My solution (again, may not be the best solution), was to convert the newly filtered 'P' image to a greyscale image ('L'). Then taking that (in this case) 3-grey image and turning the grey and white pixels to white for the black image. Then for the red image, we take the grey pixels and turn them to black while turning the existing black pixels to white to avoid the red and black from overlapping on the ePaper. This essentially sends two bw images with no overlap to the display driver which is exactly what it expects. A 'L' mode image with just black and white data and a '1' mode image is basically the same so there doesn't seem to be any gain from doing a convert. Some (maybe all) of the drivers even do the convert to '1' inside the driver.

Maybe the end goal could be to have two options for the filter method. One could be the existing method of just grabbing the red (or yellow) from the image and then displaying it as it does now. Another filter method could be to do a weighted greyscale conversion that doesn't focus on converting the actual color represented by the screen but a range of colors close to the ePaper's third color to give a more dynamic (and more colorful) output. If you're curious about weighted greyscale, I found a cool article with a formula to convert from RGB to 265-greyscale - https://entropymine.com/imageworsener/grayscale/

For now, I think just patching the existing method is good enough and then we can play around with the more advanced methods if people have time.

**Comment by robweber** [comment] 2022-03-02 21:45
I think we can all definitely agree that [8273217](https://github.com/robweber/omni-epd/commit/827321789983b9368f5e0f8d68421eec13bc6f40) was the original "source" of this particular issue; but only because of the subset of screens tested. The exhaustive testing on this confirms that with the current method some displays require an inverted b/w image while others don't. If we keep the code exactly that way it is, some displays will end up with black and white data inverted. If we revert the code then a different set of displays aren't going to work. 

The `putpalette()` solution, while simpler, doesn't seem like the best long term. We can code around the individual displays (inverted vs non-inverted) but as Waveshare updates their code it will be a constant battle to keep the list updated. It would appear that the method @aaronr8684 created yields correct results on both types of displays. Is that correct? If so that may be the best method to correct the issue "once and for all" (until it breaks again!). The threshold values should be some sort of sane default but I'd like it to be something the user can set as an `ini` value as well. Since it effects the final image produced I think it's only fair the end user has control over this. 

The more advanced, formulaic method is intriguing but could be a future PR. Ultimately offering a basic vs advanced method would be a fun enhancement. Does this direction sound like it will fix the issue for all displays that we know so far?

**Comment by aaronr8684** [comment] 2022-03-02 21:57
Yes, my original PR did fix some screens while breaking others and fortunately, it appears the new method will handle all tested screens correctly (with more to be tested going forward hopefully). 

I'll go ahead and create the PR with some INI logic built in and defaults that will take into account both red and yellow screens. I settled on the numbers in the "full else block" test, by noting what values gave the correct output on the yellow AND red palette. I'll attach the outputs below for documentation.

@robweber Would you like me to update the documentation and examples as well or do you want to handle that part?

For the more advanced "option", I wasn't suggesting that be a part of this bug fix, just an interesting thought I had while testing all of this and a possible enhancement in the future.

**Comment by aaronr8684** [comment] 2022-03-02 22:03
Filtered Image Result

Red palette:
![filtered_image_red](https://user-images.githubusercontent.com/57102156/156456900-5ab16d24-d662-482e-8ee2-63f768ffd609.png)

Yellow Palette:
![filtered_image_yellow](https://user-images.githubusercontent.com/57102156/156456937-ae76e73d-84b8-43f8-9c24-004c9891f2c5.png)

Result of the point method on `img_color` with values of 18-235:
Red:
![18to235_red-filter](https://user-images.githubusercontent.com/57102156/156457028-798ce6a9-f47b-4d49-8b23-26dac70c0a7c.png)

Yellow:
![18to235_yellow-filter](https://user-images.githubusercontent.com/57102156/156457049-12f667d7-0c41-4cb8-8692-d07d2ee1785c.png)

**Comment by robweber** [comment] 2022-03-02 22:04
I can update the documentation, that shouldn't be an issue. It will help me keep it all straight to really comb through it when complete anyway. In the PR could you reference any tested devices so I have them all in one spot for marking up the tested section of the README? 

I'll add a "help wanted" enhancement for the more advanced filter should anyone have some spare time on their hands in the future!

**Comment by missionfloyd** [comment] 2022-03-02 23:07
I think there might be some misunderstanding of how this works.

First, the image is quantized using a three-color palette: white, black, red or white, black, yellow, in that order. Then, by changing the palette index of the color we want to black and the rest to white, we can [extract](https://github.com/robweber/omni-epd/issues/7#issuecomment-825189422) pixels that are that color.

| Palette Index | 0 | 1 | 2 |
|:---|:---:|:---:|:---:|
| `image` | White | Black | Red |
| `img_black` | White | **Black** | White |
| `img_red` | White | White | **Black** |

Before you go making it more complicated, can you please try _both_ the suggestions in https://github.com/robweber/omni-epd/issues/58#issuecomment-1056336702, i.e, change that section to this:
```python
# apply the color filter to get a 3 color image
image = self._filterImage(image)

# separate out black from the other color
img_black = image.copy()
img_black.putpalette((255, 255, 255, 0, 0, 0, 255, 255, 255) + (0, 0, 0)*253)

img_color = image.copy()
img_color.putpalette((255, 255, 255, 255, 255, 255, 0, 0, 0) + (0, 0, 0)*253)

self._device.display(self._device.getbuffer(img_black.convert("RGB")), self._device.getbuffer(img_color.convert("RGB")))
```
I don't have any 3 color screens, otherwise I'd try it myself.

**Comment by aaronr8684** [comment] 2022-03-02 23:25
@missionfloyd Yes, I understand. The reason for my original PR (and commit [8273217](https://github.com/robweber/omni-epd/commit/827321789983b9368f5e0f8d68421eec13bc6f40)) was because my WaveShare (7in5b_V2) was not working as expected with the existing code. Here is the output: 
![2022-03-02 18 09 48](https://user-images.githubusercontent.com/57102156/156465369-5c6e8be6-2ada-42d5-928c-2681bc3438d1.jpg)

This prompted my PR, thinking (mistakenly) that ALL tri-color screens were broken. When the PR was merged, we discovered that while it had fixed my screen, it had also broken a few others (e.g. 5in83c and later the 2in7b_V2). Before this issue was raised, I had assumed that maybe the "old" or "yellow" method was broken and that the majority of screens would still work. After this issue was raised, I did some deeper digging into the code to figure out why the examples of all screens worked, but not the above code. This led me to my understanding of the 'P' mode in pillow remapping the data to color representation, but NOT the data itself. So to fix this, you have to make sure that the image is correctly representing black as black and white as white in the image data. Then each driver can modify the image to a buffer of values specific to each screen.

**Comment by missionfloyd** [comment] 2022-03-03 05:16
What's that the output of?

**Comment by aaronr8684** [comment] 2022-03-03 05:22
Your code and it's the same as what I saw originally

**Comment by missionfloyd** [comment] 2022-03-03 06:34
Waveshare's test images are indexed: black, then white. We've been using [white, black](https://github.com/robweber/omni-epd/blob/00f77b5d7094409eb46376de77f6655b5042abec/src/omni_epd/virtualepd.py#L50). could the order of the palette be the problem?

It shouldn't matter, all images get converted to 1-bit by the driver. Doesn't make a whole lot of sense.

**Comment by robweber** [comment] 2022-03-03 17:32
I'm really impressed by the level of detail going in to understanding how this is all working. Without a display to test it on myself I'm taking a face value what the output of the tests are showing. @missionfloyd's description of the current method for extracting the colors mirrors my understanding of how this was _supposed_ to work. That being said it's obviously not for reasons I can't decipher. 

I can't help but think part of the reason is how Waveshare has chosen to handle how it expects the images to be presented (either b/w or w/b depending on the device) but that's speculation on my part.

**Comment by aaronr8684** [comment] 2022-03-03 17:49
Yea, all I can say is that all of the waveshare devices accept a bw bmp file to the display method for the black and red images (through getbuffer). As we've discussed before, it sucks that everyone is handled differently and it appears that the 7in5b_V2 method will be the preferred direction because it uses the new send_data2 method which is considerably faster for updates.

All that to say, the test files provided by ws all work as expected across the different devices and the omni display method does not, so there seems to be a disconnect in what ws is expecting vs what omni is providing. I think (I don't know) that the it comes down to omni supplying a palettized image format when the ws drivers expect a non-palettized format. Sometimes it works and sometimes it doesn't. The two directions I think would work is 1) we can adjust the logic based on the screen type (which requires every screen to be actually tested) or 2) we can just provide a non-palettized image and assume it will probably work across all of the tri-color screens (like the supplied bmp files do).  That takes the logic of how to represent the image away from omni and onto the ws drivers. It also would likely prevent code breaking changes if the underlying logic is changed in the drivers.

**Comment by missionfloyd** [comment] 2022-03-04 05:31
If giving it a grayscale image fixes it, then converting to grayscale might be all that's needed:
```python
self._device.display(self._device.getbuffer(img_black.convert("L")), self._device.getbuffer(img_color.convert("L")))
```

**Closed** 2022-03-04 16:07 UTC
Labels: bug
